apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevator-saga
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: elevator-saga
          image: localhost:5000/elevator-saga
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: elevator-saga-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
